# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20170321_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ansible_task_id',
        ),
    ]
