"""
Django settings for auto project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

CELERY_BROKER_URL = 'redis://localhost:6379/7'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#!=c=^yzv3hiy6!psg2bm!#lk#dr&sz&ggh(vke54+r_s_(38z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Add "ws4redis" to your project's INSTALLED_APPS setting
    # http://django-websocket-redis.readthedocs.io/en/latest/installation.html
    'ws4redis',
    'core',
    'log',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'auto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Ensure that your template context contains at least these processors
                'ws4redis.context_processors.default',
                # 'django.core.context_processors.static',
            ],
        },
    },
]

# WSGI_APPLICATION = 'auto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# Specify the URL that distinguishes websocket connections from normal requests

# http://django-websocket-redis.readthedocs.io/en/latest/installation.html
WEBSOCKET_URL = '/ws/'
# If the Redis datastore uses connection settings other than the defaults, use this dictionary to override these values
WS4REDIS_CONNECTION = {
    'host': 'localhost',
    'port': 6379,
    'db': 8,
    # 'password': 'verysecret',
}
# This directive sets the number in seconds, each received message is persisted by Redis, additionally of being published on the message queue
# WS4REDIS_EXPIRE = 7200
WS4REDIS_EXPIRE = 0
# Websocket for Redis can prefix each entry in the datastore with a string. By default, this is empty.
WS4REDIS_PREFIX = 'ws'
# Override ws4redis.store.RedisStore with a customized class, in case you need an alternative implementation of that class
# WS4REDIS_SUBSCRIBER = 'myapp.redis_store.RedisSubscriber'
# This directive is required during development and ignored in production environments. It overrides Django's internal main loop and adds a URL dispatcher in front of the request handler
WSGI_APPLICATION = 'ws4redis.django_runserver.application'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'statics')]

WS4REDIS_HEARTBEAT = "ws4redis_heartbeat"