---
- hosts: all
  gather_facts: "no"
  serial: 1

  tasks:
  - name: '这是playbook test2的第一个task'
    shell: "pwd"

  pre_tasks:
  - name: "前置任务"
    shell: echo 1

  post_tasks:
  - name: "后置任务"
    shell: echo 2